name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
  - title: "🏗 Refactors"
    labels:
      - "refactor"
  - title: "🚨 Hotfixes"
    labels:
      - "hotfix"
  - title: "🐛 Fixes"
    labels:
      - "fix"
  - title: "🧰 Maintenance"
    label:
      - "chore"
category-template: "### $TITLE"
change-template: "- #$NUMBER | $TITLE"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
template: |
  ## $REPOSITORY

  $CHANGES
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
autolabeler:
  - label: "chore"
    files:
      - "*.md"
    branch:
      - '/^docs{0,1}\/.+/'
      - '/^chore\/.+/'
  - label: "fix"
    branch:
      - '/^fix\/.+/'
  - label: "hotfix"
    branch:
      - '/^hotfix\/.+/'
  - label: "feature"
    branch:
      - '/^feature\/.+/'
  - label: "refactor"
    branch:
      - '/^refactor\/.+/'
