name: Pull Requests - Coverage Check

on: ["pull_request"]

permissions:
  contents: write
  pull-requests: write

jobs:
  coverage-check:
    runs-on: ubuntu-latest
    steps:
      - uses: FlatDigital/platform-github-actions/.github/actions/golang-coverage-check@main
        with:
          doppler_token: ${{ secrets.DOPPLER_TOKEN_STG }}