name: OpenAI Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  pull_request_review_comment:
    types: [created]

concurrency:
  group:
    ${{ github.repository }}-${{ github.event.number || github.head_ref ||
    github.sha }}-${{ github.workflow }}-${{ github.event_name ==
    'pull_request_review_comment' && 'pr_comment' || 'pr' }}
  cancel-in-progress: ${{ github.event_name != 'pull_request_review_comment' }}

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: FlatDigital/platform-github-actions/.github/actions/openai-golang-code-review@main
        with:
          doppler_token: ${{ secrets.DOPPLER_TOKEN_STG }}
          github_token: ${{ secrets.GITHUB_TOKEN }}