name: Coverage & Staticcheck

on: ["pull_request"]

permissions:
  contents: write
  pull-requests: write

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: FlatDigital/platform-github-actions/.github/actions/golang-static-check@main
        with:
          doppler_token: ${{ secrets.DOPPLER_TOKEN_STG }}